# Generated by Django 5.1.4 on 2025-02-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createqr_app', '0002_alter_qrcode_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
